{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
{{ include "hammurabi.labels" . | indent 4 }}
  {{- if .Values.secrets.preserveOnUninstall }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
type: Opaque
stringData:
{{- range $key, $val := .Values.secrets.data }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}
