use crate::claude::AiInvocation;
use crate::error::HammurabiError;
use crate::models::{IssueState, TrackedIssue};
use crate::prompts;

use super::TransitionContext;

pub async fn execute(
    ctx: &TransitionContext,
    issue: &TrackedIssue,
) -> Result<(), HammurabiError> {
    tracing::info!(
        issue = issue.github_issue_number,
        "Starting spec drafting"
    );

    // Fetch issue details from GitHub
    let gh_issue = ctx
        .github
        .get_issue(issue.github_issue_number)
        .await?;

    // Get default branch
    let default_branch = ctx.github.get_default_branch().await?;

    // Create worktree
    let worktree_path = ctx
        .worktree
        .create_worktree(issue.github_issue_number, "spec", &default_branch)
        .await?;

    let worktree_str = worktree_path
        .to_str()
        .ok_or_else(|| HammurabiError::Worktree("invalid worktree path".to_string()))?
        .to_string();

    // Seed CLAUDE.md
    let claude_md = prompts::claude_md_for_spec(&gh_issue.title, &gh_issue.body);
    ctx.worktree
        .seed_file(&worktree_path, "CLAUDE.md", &claude_md)
        .await?;

    // Invoke AI
    let prompt = prompts::spec_drafting_prompt(&gh_issue.title, &gh_issue.body);
    let model = ctx.config.ai_model_for_task("spec").to_string();
    let max_turns = ctx.config.ai_max_turns_for_task("spec");
    let effort = ctx.config.ai_effort_for_task("spec").to_string();

    let result = ctx
        .ai
        .invoke(AiInvocation {
            model: model.clone(),
            max_turns,
            effort,
            worktree_path: worktree_str.clone(),
            prompt,
        })
        .await?;

    // Log usage
    ctx.db
        .log_usage(
            issue.id,
            None,
            "spec_drafting",
            result.input_tokens,
            result.output_tokens,
            &model,
        )?;

    // Push branch
    let branch_name = format!("hammurabi/{}-spec", issue.github_issue_number);
    ctx.worktree.push_branch(&branch_name).await?;

    // Create PR
    let pr_title = format!("Spec: {}", gh_issue.title);
    let pr_body = format!(
        "Auto-generated specification for #{}\n\n---\n*Generated by Hammurabi*",
        issue.github_issue_number
    );
    let pr_number = ctx
        .github
        .create_pull_request(&pr_title, &branch_name, &default_branch, &pr_body)
        .await?;

    // Update DB
    ctx.db
        .update_issue_state(issue.id, IssueState::AwaitSpecApproval, Some(IssueState::SpecDrafting))?;
    ctx.db.update_issue_spec_pr(issue.id, pr_number)?;
    ctx.db
        .update_issue_worktree(issue.id, Some(&worktree_str))?;

    // Post comment
    ctx.github
        .post_issue_comment(
            issue.github_issue_number,
            &format!(
                "Spec PR opened: #{}. Please review and merge to proceed.",
                pr_number
            ),
        )
        .await?;

    tracing::info!(
        issue = issue.github_issue_number,
        pr = pr_number,
        "Spec PR created"
    );

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::claude::mock::MockAiAgent;
    use crate::claude::AiResult;
    use crate::config::Config;
    use crate::db::Database;
    use crate::github::mock::MockGitHubClient;
    use crate::github::GitHubIssue;
    use crate::worktree::mock::MockWorktreeManager;
    use std::sync::Arc;

    fn test_config() -> Config {
        Config {
            repo: "owner/repo".to_string(),
            owner: "owner".to_string(),
            repo_name: "repo".to_string(),
            poll_interval: 60,
            max_concurrent_agents: 3,
            tracking_label: "hammurabi".to_string(),
            stale_timeout_days: 7,
            api_retry_count: 3,
            ai_model: "test-model".to_string(),
            ai_max_turns: 50,
            ai_effort: "high".to_string(),
            approvers: vec!["alice".to_string()],
            github_token: "token".to_string(),
            spec: None,
            decompose: None,
            implement: None,
        }
    }

    #[tokio::test]
    async fn test_spec_drafting_creates_pr() {
        let tmp = std::env::temp_dir().join("hammurabi-test-spec-draft");
        let _ = tokio::fs::remove_dir_all(&tmp).await;

        let gh = Arc::new(MockGitHubClient::new());
        gh.add_issue(GitHubIssue {
            number: 1,
            title: "Add feature X".to_string(),
            body: "We need feature X".to_string(),
            labels: vec!["hammurabi".to_string()],
            state: "Open".to_string(),
        });

        let ai = Arc::new(MockAiAgent::new());
        ai.set_default_response(AiResult {
            content: "# SPEC\n\nFeature X spec".to_string(),
            session_id: Some("sess-1".to_string()),
            input_tokens: 100,
            output_tokens: 200,
        });

        let wt = Arc::new(MockWorktreeManager::new(tmp.clone()));
        let db = Arc::new(Database::open(":memory:").unwrap());
        db.insert_issue(1, "Add feature X").unwrap();
        let issue = db.get_issue(1).unwrap().unwrap();

        let ctx = TransitionContext {
            github: gh.clone(),
            ai,
            worktree: wt.clone(),
            db: db.clone(),
            config: Arc::new(test_config()),
        };

        execute(&ctx, &issue).await.unwrap();

        // Verify state updated
        let updated = db.get_issue(1).unwrap().unwrap();
        assert_eq!(updated.state, IssueState::AwaitSpecApproval);
        assert!(updated.spec_pr_number.is_some());

        // Verify PR was created
        let prs = gh.created_prs.lock().unwrap();
        assert_eq!(prs.len(), 1);
        assert!(prs[0].0.contains("Spec:"));

        // Verify worktree was created
        let wts = wt.created_worktrees.lock().unwrap();
        assert_eq!(wts.len(), 1);
        assert_eq!(wts[0].0, 1);
        assert_eq!(wts[0].1, "spec");

        // Verify usage logged
        let usage = db.get_usage_by_issue(issue.id).unwrap();
        assert_eq!(usage.len(), 1);
        assert_eq!(usage[0].transition, "spec_drafting");

        // Verify comment posted
        let comments = gh.created_comments.lock().unwrap();
        assert_eq!(comments.len(), 1);

        let _ = tokio::fs::remove_dir_all(&tmp).await;
    }
}
