use crate::claude::AiInvocation;
use crate::error::HammurabiError;
use crate::hooks;
use crate::models::{IssueState, TrackedIssue};
use crate::prompts;

use super::TransitionContext;

pub async fn execute(
    ctx: &TransitionContext,
    issue: &TrackedIssue,
    feedback: Option<&str>,
) -> Result<(), HammurabiError> {
    tracing::info!(
        issue = issue.github_issue_number,
        feedback = feedback.is_some(),
        "Starting spec drafting"
    );

    // Fetch issue details from GitHub
    let gh_issue = ctx.github.get_issue(issue.github_issue_number).await?;

    // Get default branch
    let default_branch = ctx.github.get_default_branch().await?;

    // Create temporary worktree for AI to explore the repo
    let worktree_path = ctx
        .worktree
        .create_worktree(issue.github_issue_number, "spec", &default_branch)
        .await?;

    let worktree_str = worktree_path
        .to_str()
        .ok_or_else(|| HammurabiError::Worktree("invalid worktree path".to_string()))?
        .to_string();

    // Run after_create hook
    let hook_timeout = hooks::hooks_timeout(&ctx.config.hooks);
    hooks::run_hook(
        "after_create",
        ctx.config.hooks.after_create.as_deref(),
        &worktree_path,
        hook_timeout,
    )
    .await?;

    // Seed CLAUDE.md
    let claude_md = prompts::claude_md_for_spec(&gh_issue.title, &gh_issue.body);
    ctx.worktree
        .seed_file(&worktree_path, "CLAUDE.md", &claude_md)
        .await?;

    // Invoke AI with optional feedback
    let prompt = prompts::spec_drafting_prompt(&gh_issue.title, &gh_issue.body, feedback);
    let model = ctx.config.ai_model_for_task("spec").to_string();
    let max_turns = ctx.config.ai_max_turns_for_task("spec");
    let effort = ctx.config.ai_effort_for_task("spec").to_string();

    // Run before_run hook
    hooks::run_hook(
        "before_run",
        ctx.config.hooks.before_run.as_deref(),
        &worktree_path,
        hook_timeout,
    )
    .await?;

    let ai_result = ctx
        .ai
        .invoke(AiInvocation {
            model: model.clone(),
            max_turns,
            effort,
            worktree_path: worktree_str.clone(),
            prompt,
            timeout_secs: ctx.config.ai_timeout_for_task("spec"),
            stall_timeout_secs: ctx.config.ai_stall_timeout_for_task("spec"),
        })
        .await;

    // Run after_run hook (best-effort, regardless of AI result)
    hooks::run_hook_best_effort(
        "after_run",
        ctx.config.hooks.after_run.as_deref(),
        &worktree_path,
        hook_timeout,
    )
    .await;

    let result = ai_result?;

    // Log usage
    ctx.db.log_usage(
        issue.id,
        None,
        "spec_drafting",
        result.input_tokens,
        result.output_tokens,
        &model,
    )?;

    // Remove seeded CLAUDE.md before reading spec output
    let _ = tokio::fs::remove_file(worktree_path.join("CLAUDE.md")).await;

    // Read spec content from worktree (AI writes SPEC.md there)
    let spec_path = worktree_path.join("SPEC.md");
    let spec_content = tokio::fs::read_to_string(&spec_path).await.unwrap_or_else(|_| {
        // Fallback: use AI output directly if no SPEC.md was written
        result.content.clone()
    });

    // Clean up worktree
    hooks::run_hook_best_effort(
        "before_remove",
        ctx.config.hooks.before_remove.as_deref(),
        &worktree_path,
        hook_timeout,
    )
    .await;
    let _ = ctx.worktree.remove_worktree(&worktree_path).await;

    // Post spec as issue comment
    let comment_body = format!(
        "## Spec\n\n{}\n\n---\nReply `/approve` to proceed with implementation, or provide feedback to revise.\n\n*Generated by Hammurabi*",
        spec_content
    );
    let comment_id = ctx
        .github
        .post_issue_comment(issue.github_issue_number, &comment_body)
        .await?;

    // Update DB
    ctx.db.update_issue_state(
        issue.id,
        IssueState::AwaitSpecApproval,
        Some(IssueState::SpecDrafting),
    )?;
    ctx.db.update_issue_spec_comment(issue.id, comment_id)?;
    ctx.db
        .update_issue_spec_content(issue.id, &spec_content)?;
    ctx.db.update_issue_last_comment(issue.id, comment_id)?;
    ctx.db.update_issue_worktree(issue.id, None)?;

    tracing::info!(
        issue = issue.github_issue_number,
        comment_id = comment_id,
        "Spec posted as comment"
    );

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::claude::mock::MockAiAgent;
    use crate::claude::AiResult;
    use crate::config::Config;
    use crate::db::Database;
    use crate::github::mock::MockGitHubClient;
    use crate::github::GitHubIssue;
    use crate::worktree::mock::MockWorktreeManager;
    use std::sync::Arc;

    fn test_config() -> Config {
        Config {
            repo: "owner/repo".to_string(),
            owner: "owner".to_string(),
            repo_name: "repo".to_string(),
            poll_interval: 60,
            tracking_label: "hammurabi".to_string(),
            stale_timeout_days: 7,
            api_retry_count: 3,
            ai_model: "test-model".to_string(),
            ai_max_turns: 50,
            ai_effort: "high".to_string(),
            ai_timeout_secs: 3600,
            ai_stall_timeout_secs: 300,
            ai_max_retries: 2,
            max_concurrent_agents: 5,
            hooks: crate::config::HooksConfig::default(),
            approvers: vec!["alice".to_string()],
            github_auth: crate::config::GitHubAuth::Token("token".to_string()),
            spec: None,
            implement: None,
        }
    }

    #[tokio::test]
    async fn test_spec_drafting_posts_comment() {
        let tmp = std::env::temp_dir().join("hammurabi-test-spec-draft");
        let _ = tokio::fs::remove_dir_all(&tmp).await;

        let gh = Arc::new(MockGitHubClient::new());
        gh.add_issue(GitHubIssue {
            number: 1,
            title: "Add feature X".to_string(),
            body: "We need feature X".to_string(),
            labels: vec!["hammurabi".to_string()],
            state: "Open".to_string(),
        });

        let ai = Arc::new(MockAiAgent::new());
        ai.set_default_response(AiResult {
            content: "# SPEC\n\nFeature X spec".to_string(),
            session_id: Some("sess-1".to_string()),
            input_tokens: 100,
            output_tokens: 200,
        });

        let wt = Arc::new(MockWorktreeManager::new(tmp.clone()));
        let db = Arc::new(Database::open(":memory:").unwrap());
        db.insert_issue(1, "Add feature X").unwrap();
        let issue = db.get_issue(1).unwrap().unwrap();

        let ctx = TransitionContext {
            github: gh.clone(),
            ai,
            worktree: wt.clone(),
            db: db.clone(),
            config: Arc::new(test_config()),
        };

        execute(&ctx, &issue, None).await.unwrap();

        // Verify state updated
        let updated = db.get_issue(1).unwrap().unwrap();
        assert_eq!(updated.state, IssueState::AwaitSpecApproval);
        assert!(updated.spec_comment_id.is_some());
        assert!(updated.spec_content.is_some());

        // Verify comment posted (not PR)
        let comments = gh.created_comments.lock().unwrap();
        assert_eq!(comments.len(), 1);
        assert!(comments[0].1.contains("Spec"));
        assert!(comments[0].1.contains("/approve"));

        // Verify NO PRs were created
        let prs = gh.created_prs.lock().unwrap();
        assert_eq!(prs.len(), 0);

        // Verify usage logged
        let usage = db.get_usage_by_issue(issue.id).unwrap();
        assert_eq!(usage.len(), 1);
        assert_eq!(usage[0].transition, "spec_drafting");

        let _ = tokio::fs::remove_dir_all(&tmp).await;
    }
}
