use crate::error::HammurabiError;
use crate::hooks;
use crate::models::{IssueState, TrackedIssue};
use crate::prompts;

use super::{AiLifecycleParams, TransitionContext};

pub async fn execute(
    ctx: &TransitionContext,
    issue: &TrackedIssue,
    feedback: Option<&str>,
) -> Result<(), HammurabiError> {
    tracing::info!(
        issue = issue.github_issue_number,
        feedback = feedback.is_some(),
        "Starting spec drafting"
    );

    let gh_issue = ctx.github.get_issue(issue.github_issue_number).await?;
    let default_branch = ctx.github.get_default_branch().await?;

    let claude_md = prompts::claude_md_for_spec(&gh_issue.title, &gh_issue.body);
    let prompt = prompts::spec_drafting_prompt(&gh_issue.title, &gh_issue.body, feedback);

    let lifecycle = super::run_ai_lifecycle(
        ctx,
        AiLifecycleParams {
            issue_number: issue.github_issue_number,
            task_name: "spec".to_string(),
            base_branch: default_branch,
            claude_md,
            prompt,
            ai_task: "spec".to_string(),
            prepend_claude_md: false,
        },
    )
    .await?;

    let model = ctx.config.ai_model_for_task("spec").to_string();
    ctx.db.log_usage(
        issue.id,
        None,
        "spec_drafting",
        lifecycle.ai_result.input_tokens,
        lifecycle.ai_result.output_tokens,
        &model,
    )?;

    // Remove seeded instruction file before reading spec output
    let _ = tokio::fs::remove_file(lifecycle.worktree_path.join(lifecycle.seed_filename)).await;

    // Read spec content from worktree (AI writes SPEC.md there)
    let spec_path = lifecycle.worktree_path.join("SPEC.md");
    let spec_content = tokio::fs::read_to_string(&spec_path)
        .await
        .unwrap_or_else(|_| {
            // Fallback: use AI output directly if no SPEC.md was written
            lifecycle.ai_result.content.clone()
        });

    // Clean up worktree
    let hook_timeout = hooks::hooks_timeout(&ctx.config.hooks);
    hooks::run_hook_best_effort(
        "before_remove",
        ctx.config.hooks.before_remove.as_deref(),
        &lifecycle.worktree_path,
        hook_timeout,
    )
    .await;
    let _ = ctx.worktree.remove_worktree(&lifecycle.worktree_path).await;

    // Post spec as issue comment
    let comment_body = format!(
        "## Spec\n\n{}\n\n---\nReply `/approve` to proceed with implementation, or provide feedback to revise.\n\n*Generated by Hammurabi*",
        spec_content
    );
    let comment_id = ctx
        .publisher
        .post(issue.github_issue_number, &comment_body)
        .await?;

    // Update DB
    ctx.db.update_issue_state(
        issue.id,
        IssueState::AwaitSpecApproval,
        Some(IssueState::SpecDrafting),
    )?;
    ctx.db.update_issue_spec_comment(issue.id, comment_id)?;
    ctx.db.update_issue_spec_content(issue.id, &spec_content)?;
    ctx.db.update_issue_last_comment(issue.id, comment_id)?;
    ctx.db.update_issue_worktree(issue.id, None)?;

    tracing::info!(
        issue = issue.github_issue_number,
        comment_id = comment_id,
        "Spec posted as comment"
    );

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::agents::mock::MockAiAgent;
    use crate::agents::{AgentKind, AiResult};
    use crate::db::Database;
    use crate::github::mock::MockGitHubClient;
    use crate::github::GitHubIssue;
    use crate::worktree::mock::MockWorktreeManager;
    use std::sync::Arc;

    use crate::transitions::test_helpers::{test_config, test_registry_with};

    #[tokio::test]
    async fn test_spec_drafting_posts_comment() {
        let tmp = std::env::temp_dir().join("hammurabi-test-spec-draft");
        let _ = tokio::fs::remove_dir_all(&tmp).await;

        let gh = Arc::new(MockGitHubClient::new());
        gh.add_issue(GitHubIssue {
            number: 1,
            title: "Add feature X".to_string(),
            body: "We need feature X".to_string(),
            labels: vec!["hammurabi".to_string()],
            state: "Open".to_string(),
            user_login: "alice".to_string(),
        });

        let ai = Arc::new(MockAiAgent::new());
        ai.set_default_response(AiResult {
            content: "# SPEC\n\nFeature X spec".to_string(),
            session_id: Some("sess-1".to_string()),
            input_tokens: 100,
            output_tokens: 200,
            agent_kind: AgentKind::ClaudeCli,
            tool_summary: Vec::new(),
        });

        let wt = Arc::new(MockWorktreeManager::new(tmp.clone()));
        let db = Arc::new(Database::open(":memory:").unwrap());
        db.insert_issue("owner/repo", 1, "Add feature X").unwrap();
        let issue = db.get_issue("owner/repo", 1).unwrap().unwrap();

        let ctx = TransitionContext {
            github: gh.clone(),
            publisher: std::sync::Arc::new(crate::publisher::GithubPublisher::new(gh.clone())),
            agents: test_registry_with(ai),
            worktree: wt.clone(),
            db: db.clone(),
            config: Arc::new(test_config()),
        };

        execute(&ctx, &issue, None).await.unwrap();

        // Verify state updated
        let updated = db.get_issue("owner/repo", 1).unwrap().unwrap();
        assert_eq!(updated.state, IssueState::AwaitSpecApproval);
        assert!(updated.spec_comment_id.is_some());
        assert!(updated.spec_content.is_some());

        // Verify comment posted (not PR)
        let comments = gh.created_comments.lock().unwrap();
        assert_eq!(comments.len(), 1);
        assert!(comments[0].1.contains("Spec"));
        assert!(comments[0].1.contains("/approve"));

        // Verify NO PRs were created
        let prs = gh.created_prs.lock().unwrap();
        assert_eq!(prs.len(), 0);

        // Verify usage logged
        let usage = db.get_usage_by_issue(issue.id).unwrap();
        assert_eq!(usage.len(), 1);
        assert_eq!(usage[0].transition, "spec_drafting");

        let _ = tokio::fs::remove_dir_all(&tmp).await;
    }
}
